
GET http://localhost:3000/

###
GET http://localhost:8000/users

###
GET http://localhost:8000/userrelations

###
GET http://localhost:8000/states

###
GET http://localhost:8000/drivers

###
GET http://localhost:8000/cities

###
GET http://localhost:8000/address

###
GET http://localhost:8000/restaurants

###
GET http://localhost:8000/users/4

###
GET http://localhost:8000/states/1

###
GET  http://localhost:8000/drivers/1

###
GET http://localhost:8000/cities/3

###
GET http://localhost:8000/address/4

###

GET http://localhost:8000/restaurants/4

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "id": "8",
  "name": "max",
  "contact_phone": 267830,
  "phone_verified": true,
  "email": "lon@gmail.com",
  "email_verified": true,
  "confirmation_code": null,
  "password": 234500
  }

###
POST http://localhost:8000/states
 Content-Type: application/json

 {
  "id": 6,
  "name": "meru",
  "code": 34011
}

###
POST http://localhost:8000/drivers
 Content-Type: application/json

 {
 "id": 4,
  "car_make": "isuzu",
  "car_model": "probox",
  "car_year": 2023,
  "userId": 2,
  "online": true,
  "delivering": true
 
}
###
POST http://localhost:8000/cities
 Content-Type: application/json

 {
    "id": 7,
    "name": "embu",
    "stateId": 2
  }

###
POST http://localhost:8000/restaurants
 Content-Type: application/json

 {
    "id": 7,
    "name": "hotel-transolvinyia",
    "street_address": "1023",
    "zip_code": "32-00",
    "cityId": 3,
    "created_at": null,
    "updated_at": null
  }


###
PUT http://localhost:8000/users/3
Content-Type: application/json

{
   
  "name": "karn"
}

###
PUT http://localhost:8000/states/2
Content-Type: application/json
  
  {
    
    "name": "mombasa"
  }

###
PUT http://localhost:8000/drivers/4
Content-Type: application/json

{ 
  "car_model": "audi"
}

###
PUT  http://localhost:8000/cities/3
 Content-Type: application/json

 {
   "name": "sagana"
 }

###
PUT  http://localhost:8000/restaurants/6
Content-Type: application/json

 {
   "name": "krusty krab"
 }



###
DELETE http://localhost:8000/users/2

###
DELETE http://localhost:8000/states/6

###
DELETE http://localhost:8000/drivers/4

###
DELETE http://localhost:8000/cities/5

###
DELETE http://localhost:8000/restaurants/7