
GET http://localhost:8000/ok

##----------------------------------admin authority-------------------------------------------------
###
GET http://localhost:8000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE
###
GET http://localhost:8000/relation/usercommentrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE
###
GET http://localhost:8000/relation/useraddressrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/relation/userorderrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/relation/orderscommentrelations

###
GET http://localhost:8000/relation/ordersaddressrelations

###
GET http://localhost:8000/relation/orderrestaurantrelations

###
GET http://localhost:8000/relation/restaurantcityrelations

###
GET http://localhost:8000/relation/restaurantmenurelations

###
GET http://localhost:8000/relation/restaurantorderrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/relation/driverUserrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/relation/userdriverrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE


###
GET http://localhost:8000/userrelations/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/states
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/relation/Menuitemrestaurantrelations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE

###
GET http://localhost:8000/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE


# -------------------------------------------------user authority----------------------------------------------------------------------------------------------
###
GET http://localhost:8000/relation/statecityrelations/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0b20iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODI4NzYxMH0.tdI-igrKXBwW0rRGCteXD9PfWLKk6uQplFrlkJ9UC10
###
GET http://localhost:8000/relation/singleuserdriversrelations/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjg2NTk3fQ.U-gMFpEFMYCKqfJctXaOnP2ikZq2BhUFM_O-J5lXFNE
###
GET http://localhost:8000/users/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0b20iLCJyb2xlIjoidXNlciIsImV4cCI6MTcxODI3ODc4Nn0.tOy4xwthrcwstxoX17uHaM1zFdPnaI39Mju8EXAFFCE


###
GET http://localhost:8000/drivers

###
GET http://localhost:8000/limitaddress?limit=1

###
GET http://localhost:8000/cities

###
GET http://localhost:8000/citiesrelations


###
GET http://localhost:8000/restaurants

###
GET http://localhost:8000/orders

###
GET http://localhost:8000/categoryrelation


###
GET http://localhost:8000/states/1

###
GET  http://localhost:8000/drivers/1

###
GET http://localhost:8000/cities/3

###
GET http://localhost:8000/address/1

###

GET http://localhost:8000/restaurants/4

###
POST http://localhost:8000/users
Content-Type: application/json


  {
    "id": 2,
    "name": "joe",
    "contact_phone": 0924533,
    "phone_verified": false,
    "email": "tjoe@gmail.com",
    "email_verified": false,
    "confirmation_code": null,
    "password": 1400
  }

###
POST http://localhost:8000/orders
Content-Type: application/json

{
    "id": 7,
    "estimated_delivery_time": null,
    "actual_delivery_time": null,
    "restaurantId": 1,
    "deliveryAddressId": 1,
    "userId": 1,
    "driverId": 1,
    "price": "1000",
    "discount": "50",
    "final_price": "950",
    "comment": "none",
    "created_at": null,
    "updated_at": null
  }

###
POST http://localhost:8000/states
 Content-Type: application/json

 {
  "id": 6,
  "name": "meru",
  "code": 34011
}

###
POST http://localhost:8000/drivers
 Content-Type: application/json

 {
 "id": 5,
  "car_make": "jaguar",
  "car_model": "jaguar-xj",
  "car_year": 2018,
  "userId": 8,
  "online": true,
  "delivering": true
 
}
###
POST http://localhost:8000/cities
 Content-Type: application/json

 {
    "id": 6,
    "name": "othaya",
    "stateId": 3
  }

###
POST http://localhost:8000/restaurants
 Content-Type: application/json

 {
    "id": 7,
    "name": "hotel-transolvinyia",
    "street_address": "1023",
    "zip_code": "32-00",
    "cityId": 3,
    "created_at": null,
    "updated_at": null
  }


###
PUT http://localhost:8000/users/3
Content-Type: application/json

{
   
  "name": "karn"
}

###
PUT http://localhost:8000/states/2
Content-Type: application/json
  
  {
    
    "name": "mombasa"
  }

###
PUT http://localhost:8000/drivers/4
Content-Type: application/json

{ 
  "car_model": "audi"
}

###
PUT  http://localhost:8000/cities/3
 Content-Type: application/json

 {
   "name": "sagana"
 }

###
PUT  http://localhost:8000/restaurants/6
Content-Type: application/json

 {
   "name": "krusty krab"
 }



###
DELETE http://localhost:8000/users/8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ6YXJhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzE4Mjc4OTQ4fQ.AtK56kIJGZWrejHSz8_wbQfyvJ8aVFj6DdcfH6-wp-g
###

###
DELETE http://localhost:8000/states/6

###
DELETE http://localhost:8000/drivers/4

###
DELETE http://localhost:8000/cities/5

###
DELETE http://localhost:8000/restaurants/7

###
POST  http://localhost:8000/auth/register
Content-Type: application/json

{
   "userId": 3,
  "username": "brayo",
  "password": "1300",
  "role": "user"
}

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
   
  "username": "tom",
  "password": "3456"
}